'use strict';

process.env.NODE_ENV = 'test';

const { suite, test } = require('mocha');
const app = require('../server');
const supertest = require('supertest');

suite('binary routes', () => {
  test('GET /binary', (done) => {
    supertest(app)
      .get('/api/facilities/232074/?apikey=28865E612CC64AB3A06BF724737A08DC&full')
      .expect(200, '0')
      .expect('Content-Type', /json/)
      .end(done);
  });
});

/* eslint-disable */
// const response = { FacilityEmail: '',
//   FacilityLongitude: -121.39555555555556,
//   FacilityDescription: '<h2>Overview</h2>Situated on the banks of the South Fork Skykomish River in Mt. Baker-Snoqualmie National Forest, Money Creek campground offers some of the most stunning scenery in the northern Cascade Range in Washington.<br /><br />Scattered beneath a towering canopy of old-growth forest, the sites in this campground are widely spaced and several are at the rivers edge, making it an ideal setting for visitors wanting to camp in a private, rustic setting. <h4>Natural Features:</h4>Hemmed in by several designated wilderness areas, the Mt. Baker-Snoqualmie National Forest showcases rugged peaks, sparkling alpine lakes and old-growth forests.<br /><br />Mt. Baker, the most prominent feature of the Mt. Baker Wilderness Area, dominates the landscape on a clear day. Rising to an elevation of 10,781 feet, the active volcano from which the forest takes its name is perpetually snow-capped and mantled with an extensive network of creeping glaciers. Mt. Bakers summit, Grant Peak, is actually a 1,300-foot-deep mound of ice, which hides a massive volcanic crater.<br /><br />Wildlife in the area include mountain goats, coyotes, pine marten and a variety of migratory birds and native fish.<h4>Recreation:</h4>In addition to being a prime location for hiking, and fishing in summer and early fall, Money Creek offers excellent skiing and snowshoeing in the winter months.<br /><br /> The Mt. Baker-Snoqualmie National Forests 1,500 miles of trails can entice any hiker to get outdoors. From smooth paths meandering through deep quiet forests to challenging ascents up boulder-studded mountains, opportunities abound for every skill level.<br /><br />Nearby Barclay Creek Trail is an easier hike that follows Barclay Creek through diverse forest until reaching Barclay Lake at an elevation of 2,422 feet. Along the trail, hikers will encounter old growth trees, deer ferns, trillium, wood violets, bleeding hearts and salmon berries in season. Cedar boardwalks lead to a log bridge that crosses Barclay Creek. Once over the bridge, visitors will arrive at the lake and can take in an outstanding view of the north wall of Baring Mountain, dramatically rising 3,700 feet above the lake. <h4>Facilities:</h4>Money Creek campground offers standard sites, accommodating both tent and RV camping. Picnic tables, vault toilets and drinking water are also available.<br /><br /> The nearby Miller River/Money Creek Winter Sports Area is popular base for winter activities.<h4>Nearby Attractions:</h4>The nearby Stevens Pass Historic District offers education on the areas colorful railroad and mining history. The slopes at Stevens Pass Ski Area are only a two hour drive from Money Creek campground.<br /><br /><br /><br /> Visitors enjoy the North Cascades and Mt. Rainer National Parks, where interpretive programs and exhibits offer education about the diverse landscape and history of the area.',
//   FacilityLatitude: 47.721111111111114,
//   ACTIVITY:
//    [ { FacilityActivityFeeDescription: '',
//        ActivityID: 5,
//        FacilityActivityDescription: 'Biking',
//        ActivityName: 'BIKING',
//        FacilityID: 232074 },
//      { FacilityActivityFeeDescription: 'Camping',
//        ActivityID: 9,
//        FacilityActivityDescription: 'Camping',
//        ActivityName: 'CAMPING',
//        FacilityID: 232074 },
//      { FacilityActivityFeeDescription: '',
//        ActivityID: 11,
//        FacilityActivityDescription: 'Fishing',
//        ActivityName: 'FISHING',
//        FacilityID: 232074 },
//      { FacilityActivityFeeDescription: '',
//        ActivityID: 14,
//        FacilityActivityDescription: 'Hiking',
//        ActivityName: 'HIKING',
//        FacilityID: 232074 } ],
//   FacilityTypeDescription: 'Camping',
//   FacilityPhone: '541-338-7869',
//   FacilityMapURL: '',
//   FacilityReservationURL: '',
//   FacilityDirections: 'From Everett, Washington, take Highway 2 toward Monroe. From Monroe goeast approximately 30 miles to campground sign. Turn south and travel a mileto campground.',
//   FacilityName: 'Money Creek Campground',
//   TOUR: [],
//   Keywords: '',
//   FacilityUseFeeDescription: '',
//   StayLimit: '',
//   ORGANIZATION:
//    [ { OrgAbbrevName: 'FS',
//        OrgJurisdictionType: 'Federal',
//        OrgType: 'Department of Agriculture',
//        LastUpdatedDate: '{ts \'2007-02-26 00:00:00\'}',
//        OrgURLText: 'fs.fed.us',
//        OrgURLAddress: 'http://www.fs.fed.us',
//        OrgImageURL: 'fs.jpg',
//        OrgParentID: 163,
//        OrgID: 131,
//        OrgName: 'USDA Forest Service' } ],
//   LINK:
//    [ { EntityType: 'Facility',
//        EntityID: 232074,
//        LinkType: '',
//        Description: 'Hoodoo Recreation Services',
//        URL: 'http://www.hoodoo.com/',
//        EntityLinkID: 13566630,
//        Title: 'Forest Service Concessionaire' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        LinkType: '',
//        Description: 'Washington State Road Conditions',
//        URL: 'http://www.wsdot.wa.gov/',
//        EntityLinkID: 13566631,
//        Title: 'Washington State Road Conditions' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        LinkType: '',
//        Description: 'Washington State Tourism',
//        URL: 'http://www.experiencewashington.com/',
//        EntityLinkID: 13566632,
//        Title: 'Washington State Tourism' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        LinkType: '',
//        Description: 'Print Facility Map',
//        URL: 'http://www.recreation.gov/webphotos/facilitymaps/70298_MONE.pdf',
//        EntityLinkID: 13566633,
//        Title: 'Print Facility Map' } ],
//   GEOJSON:
//    { COORDINATES: [ -121.39555555555556, 47.721111111111114 ],
//      TYPE: 'Point' },
//   LastUpdatedDate: '2016-09-22',
//   CAMPSITE:
//    [ { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77167',
//        CampsiteID: 77167,
//        CampsiteName: 24 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77176',
//        CampsiteID: 77176,
//        CampsiteName: 3 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77224',
//        CampsiteID: 77224,
//        CampsiteName: 13 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77269',
//        CampsiteID: 77269,
//        CampsiteName: 1 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77285',
//        CampsiteID: 77285,
//        CampsiteName: 15 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77374',
//        CampsiteID: 77374,
//        CampsiteName: 6 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77380',
//        CampsiteID: 77380,
//        CampsiteName: 10 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77386',
//        CampsiteID: 77386,
//        CampsiteName: 17 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77439',
//        CampsiteID: 77439,
//        CampsiteName: 20 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77493',
//        CampsiteID: 77493,
//        CampsiteName: 11 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77579',
//        CampsiteID: 77579,
//        CampsiteName: '004 Multi' },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77580',
//        CampsiteID: 77580,
//        CampsiteName: 7 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77604',
//        CampsiteID: 77604,
//        CampsiteName: 9 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77605',
//        CampsiteID: 77605,
//        CampsiteName: 18 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77653',
//        CampsiteID: 77653,
//        CampsiteName: 5 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77762',
//        CampsiteID: 77762,
//        CampsiteName: 12 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77763',
//        CampsiteID: 77763,
//        CampsiteName: 21 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77799',
//        CampsiteID: 77799,
//        CampsiteName: 8 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77830',
//        CampsiteID: 77830,
//        CampsiteName: 23 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77872',
//        CampsiteID: 77872,
//        CampsiteName: 14 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77876',
//        CampsiteID: 77876,
//        CampsiteName: '016 Closed' },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77907',
//        CampsiteID: 77907,
//        CampsiteName: 22 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77930',
//        CampsiteID: 77930,
//        CampsiteName: 19 },
//      { ResourceLink: 'https://ridb.recreation.gov/api/v1/facilities/232074/campsites/77949',
//        CampsiteID: 77949,
//        CampsiteName: 2 } ],
//   MEDIA:
//    [ { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192344,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/63939.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192357,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/63952.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192430,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/64028.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192500,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/64098.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192535,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/64133.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' },
//      { EntityType: 'Facility',
//        EntityID: 232074,
//        Credits: '',
//        Description: '',
//        Subtitle: '',
//        EmbedCode: '',
//        EntityMediaID: 1192563,
//        Height: 360,
//        MediaType: 'Image',
//        URL: 'http://ridb.recreation.gov/images/64162.jpg',
//        Width: 540,
//        Title: 'Money Creek Campground' } ],
//   FacilityAdaAccess: '',
//   EVENT: [],
//   LegacyFacilityID: 70298,
//   PERMITENTRANCE: [],
//   FACILITYADDRESS:
//    [ { FacilityAddressID: 15569519,
//        PostalCode: 98288,
//        FacilityAddressType: '',
//        AddressStateCode: 'WA',
//        FacilityStreetAddress1: 'Old Cascade Highway',
//        City: 'King',
//        FacilityStreetAddress3: '',
//        FacilityStreetAddress2: '',
//        FacilityID: 232074,
//        AddressCountryCode: 'USA' } ],
//   OrgFacilityID: 'AN370298',
//   FacilityID: 232074 };
