/* eslint-disable camelcase */
/* eslint-disable max-len */
'use strict';

exports.seed = function(knex) {
  return knex('facilities').del()
    .then(() => {
      return knex('facilities').insert([{
        id: 1,
        created_at: new Date('2016-09-11 00:00:00 UTC'),
        updated_at: new Date('2016-09-11 00:00:00 UTC'),
        deleted_at: null,
        ridb_facility_id: 201792,
        facility_name: 'Liberty Campground',
        facility_email: 'BLM_OR_SP_Mail@blm.gov',
        facility_latitude: 47.2487,
        facility_longitude: -120.6776,
        facility_description: 'Liberty is a dispersed campground which lies along a creek in a grove of cottonwoods, and is surrounded by forested mountains. The open, forested setting and USFS trails nearby make this a popular area.',
        facility_type_description: '',
        facility_phone: '509-536-1200',
        facility_map_url: '',
        facility_reservation_url: ' ',
        facility_directions: 'Kittitas County, 12 miles south of Swauk Pass on Hwy. 97. Take the Liberty Road one mile, and the BLM site is on the right.',
        keywords: '',
        facility_use_fee_description: '',
        stay_limit: '',
        last_updated_date: new Date('2012-06-02'),
        facility_ada_access: '',
        legacy_facility_id: 'BLM',
        org_facility_id: '',
        facility_address_type: '',
        facility_street_address1: 'Spokane District Office',
        facility_street_address2: ' ',
        facility_street_address3: ' 1103 N. Fancher Road',
        city: 'Spokane',
        address_state_code: 'WA',
        postal_code: '99212',
        address_country_code: 'USA'
      }, {
        id: 2,
        created_at: new Date('2016-09-11 00:00:00 UTC'),
        updated_at: new Date('2016-09-11 00:00:00 UTC'),
        deleted_at: null,
        ridb_facility_id: 232023,
        facility_name: 'Boulder Creek Campground',
        facility_email: '',
        facility_latitude: 48.71416666666667,
        facility_longitude: -121.69361111111111,
        facility_description: '<h2>Overview</h2>Boulder Creek Campground sits along the banks of Boulder Creek in the stunning Mt. Baker-Snoqualmie National Forest. The unique setting offers many recreational activities and scenic views. Baker Lake is close by, and several hiking trails and climbing routes are within a short driving distance.<h4>Natural Features:</h4>The Mt. Baker-Snoqualmie National Forest showcases rugged peaks, sparkling alpine lakes and old-growth forests, providing visitors with unique and surprising landscapes.<br /><br />Mt. Baker, the most prominent feature of the Mt. Baker Wilderness, dominates the landscape on a clear day. Rising to an elevation of 10,781 feet, the active volcano is perpetually snow-capped and mantled with an extensive network of creeping glaciers. Mt. Bakers summit, Grant Peak, is a 1,300-foot-deep mound of ice, which hides a massive volcanic crater.<br /><br />Wildlife in the area includes mountain goats traversing the higher elevations to pine martens and porcupines in the forests. Migratory birds and native fish find ample habitat in the varied ecosystems as well. <h4>Recreation:</h4>The surrounding area is a prime location for hiking, climbing, boating, fishing, picnicking and horseback riding in summer and early fall, and skiing and snowshoeing in the winter months. <br /><br />Baker Lake is a popular destination for boating, water skiing, canoeing, fishing and swimming. Anglers cast for kokanee, rainbow and cutthroat trout, salmon, native char and wild steelhead. The lake is within walking distance of the campground. Boat ramps are available at Horseshoe Cove, Swift Creek and Shannon Creek Campgrounds.<br /><br />Baker Lake Trail is an easy family hike that begins in a majestic stand of Douglas fir. In 1843, a small eruption of Mt. Baker caused a forest fire, and visitors can still see the burned snags of virgin cedar trees that once dominated the area. The trail contours above the eastern shoreline of Baker Lake.<br /><br />The Shadow of the Sentinels Trail begins just south of the campground. This  accessible interpretive trail winds through a 500-year old ancient forest. Displays along the path explain the dynamics of the forest. The trail is constructed of asphalt and boardwalks with grades no greater than 8%.<h4>Facilities:</h4>Boulder Creek Campground accommodates both tent and RV campers, and contains a group site. Picnic tables, campfire rings and vault toilets are provided, but drinking water and hookups are not available. Visitors must bring their own supply of water.<h4>Nearby Attractions:</h4>Take some time to visit Cascades National Park. This unique park is like no other place on earth. It features a deep blue lake surrounded by sheer, 2,000 cliffs, two picturesque islands and a violent volcanic past. Hiking trails, a visitor center and educational programs are available.<br /><br />Traverse a portion of the spectacular Pacific Crest Trail (PCT), one of the worlds premier National Scenic Trails. This trail showcases some of North Americas most fantastic scenery as it winds its way from Mexico to Canada through California, Oregon and Washington.',
        facility_type_description: 'Camping',
        facility_phone: '541-338-7869',
        facility_map_url: '',
        facility_reservation_url: ' ',
        facility_directions: 'From Seattle, go north on I-5 to Mt Vernon. Take Exit 230 on State Highway 20. Go past Sedro-Woolley and take Baker Lake Road to Baker Lake. The campground is approximately 16 miles north of Concrete, Washington.',
        keywords: '',
        facility_use_fee_description: '',
        stay_limit: '',
        last_updated_date: new Date('2016-09-08'),
        facility_ada_access: '',
        legacy_facility_id: '70241',
        org_facility_id: 'AN370241',
        facility_address_type: '',
        facility_street_address1: 'Baker Lake Road',
        facility_street_address2: '',
        facility_street_address3: '',
        city: 'Concrete',
        address_state_code: 'WA',
        postal_code: '98237',
        address_country_code: 'USA'
      }, {
        id: 3,
        created_at: new Date('2016-09-11 00:00:00 UTC'),
        updated_at: new Date('2016-09-11 00:00:00 UTC'),
        deleted_at: null,
        ridb_facility_id: 232033,
        facility_name: 'The Dalles Campground',
        facility_email: '',
        facility_latitude: 47.07833333333333,
        facility_longitude: -121.58305555555555,
        facility_description: '<h2>Overview</h2>Situated on the banks of the White River in Mt. Baker-Snoqualmie National Forest, Dalles Campground offers visitors stunning scenery and access to a multitude of recreational activities within the Cascade region.<br /><br />Scattered beneath a towering canopy of diverse forest, the sites in this campground are widely-spaced and many are at the waters edge.<h4>Natural Features:</h4>Hemmed in by several designated wilderness areas, the Mt. Baker-Snoqualmie National Forest showcases rugged peaks, sparkling alpine lakes and old-growth forests, providing visitors with a variety of scenic landscapes.<br /><br />Mt. Rainer, the highest mountain in Washington and the Cascades range, dominates the landscape on a clear day. Rising to an elevation of 14,411 feet, the stratovolcano is perpetually snow-capped, boasting a total of 36-square miles of snowfields and glaciers. Two volcanic craters top the summit of this magnificent peak.<br /><br />Flowing water from ice caves at the base of Emmons Glacier in Mt. Rainer National Park is the source of the White River, which enters the forest and joins up with Huckleberry Creek just below the Dalles Campground.<br /><br /> Wildlife in the area include mountain goats, coyotes, pine marten and a variety of migratory birds and native fish.<h4>Recreation:</h4>Hiking and fishing top the list of recreational activities in the area.<br /><br /> For visitors wanting a glimpse at the wonders of the area, hikes for all levels and abilities abound. For a shorter hike, the John Muir Nature Trail is a half-mile, barrier-free nature trail that begins at the historic picnic shelter near the entrance of the campground. <br /><br />Marking the beginning of the Dalles River View trail at the west end of the campground loop is the &quot;Big Tree,&quot; a 700 year-old Douglas fir that measures 9.5 feet in diameter.<br /><br />Anglers will enjoy fly fishing on the White River and its tributaries, as it sustains several species of salmon and trout.<h4>Facilities:</h4>Dalles campground offers standard sites and is able to accommodate tents or RVs.<br /><br />Picnic tables and campfire rings with grills are available at each site, and vault toilets and drinking water are accessible throughout the campground.<br /><br /> A covered historic picnic shelter, constructed by the Civilian Conservation Corps, may be reserved, otherwise it is available on a first-come first-serve basis.<h4>Nearby Attractions:</h4>Visitors enjoy the North Cascades and Mt. Rainer National Parks, where interpretive programs and exhibits offer education about the diverse landscape and history of the area.',
        facility_type_description: 'Camping',
        facility_phone: '541-338-7869',
        facility_map_url: '',
        facility_reservation_url: ' ',
        facility_directions: 'From Enumclaw, Washington, go southeast on Highway 410 towards Mt. Rainierpark for approximately 26 miles to campground.',
        keywords: '',
        facility_use_fee_description: '',
        stay_limit: '',
        last_updated_date: new Date('2016-09-08'),
        facility_ada_access: '',
        legacy_facility_id: '70253',
        org_facility_id: 'AN370253',
        facility_address_type: '',
        facility_street_address1: 'Highway 410',
        facility_street_address2: '',
        facility_street_address3: '',
        city: 'Enumclaw',
        address_state_code: 'WA',
        postal_code: '98022',
        address_country_code: 'USA'
      }, {
        id: 4,
        created_at: new Date('2016-09-11 00:00:00 UTC'),
        updated_at: new Date('2016-09-11 00:00:00 UTC'),
        deleted_at: null,
        ridb_facility_id: 232035,
        facility_name: 'Denny Creek Campground',
        facility_email: '',
        facility_latitude: 47.411944444444444,
        facility_longitude: -121.44277777777778,
        facility_description: '<h2>Overview</h2>Situated near the south fork of the Snoqualmie River in Mt. Baker-Snoqualmie National Forest, Denny Creek Campground offers visitors stunning scenery and easy access to an abundance of recreational activities in the Northern Cascade Range.<br /><br />Campsites sit beneath a canopy of forest, and a few are sprinkled at the banks of Lodge Creek, which flows into the Snoqualmie. <h4>Natural Features:</h4>Hemmed in by several designated wilderness areas, this national forest showcases rugged peaks, sparkling alpine lakes and old-growth forests, providing visitors with a variety of scenic landscapes.<br /><br />On a clear day visitors can spot Mt. Baker, the most prominent feature of the Mt. Baker Wilderness Area. Rising to an elevation of 10,781 feet, this active volcano is perpetually snow-capped and mantled with an extensive network of creeping glaciers. Mt. Bakers summit, Grant Peak, is actually a 1,300-foot-deep mound of ice, which hides a massive volcanic crater.<br /><br /> Wildlife in the area include mountain goats, coyotes, pine marten and a variety of migratory birds and native fish.<h4>Recreation:</h4>In addition to being a prime location for hiking, fishing, picnicking and horseback riding in summer and early fall, Denny Creek offers excellent skiing and snowshoeing in the winter months.<br /><br /> The Asahel Curtis Nature Trail, named for one of Washingtons most renowned nature photographers, is located nearby.  This trail is a short, easy walk through one of the last remaining stands of old growth forest in the Snoqualmie Valley. The trail crosses Humpback Creek several times before rising gently into a grove of mature Douglas-fir, western hemlock and western red cedar. Mosses, ferns, orchids and a large variety of other wildflowers abound on the forest floor. <h4>Facilities:</h4>Denny Creek Campground offers 24 reservable campsites, including one group site. Picnic tables, flush toilets and drinking water are also available, as well as electrical hook-ups at a handful of sites.<h4>Nearby Attractions:</h4>Denny Creek Road, a historic wagon route used by early settlers to cross Snoqualmie Pass, can be accessed from milepost 47.<br /><br />The Verlot Public Service Center, near the South Fork Stillaguamish River, was built by the Civilian Conservation Corps from 1933 to 1942. Verlot`s handsome buildings reflect the architectural style and fine craftsmanship of the era and are listed on the National Register of Historic Places.',
        facility_type_description: 'Camping',
        facility_phone: '541-338-7869',
        facility_map_url: '',
        facility_reservation_url: ' ',
        facility_directions: 'From Seattle, take Interstate 90 east to exit 47. Go north over the freeway and follow signs 3 miles to campground.',
        keywords: '',
        facility_use_fee_description: '',
        stay_limit: '',
        last_updated_date: new Date('2016-09-08'),
        facility_ada_access: '',
        legacy_facility_id: '70256',
        org_facility_id: 'AN370256',
        facility_address_type: '',
        facility_street_address1: 'Highway I-90',
        facility_street_address2: '',
        facility_street_address3: '',
        city: 'North Bend',
        address_state_code: 'WA',
        postal_code: '98045',
        address_country_code: 'USA'
      }, {
        id: 5,
        created_at: new Date('2016-09-11 00:00:00 UTC'),
        updated_at: new Date('2016-09-11 00:00:00 UTC'),
        deleted_at: null,
        ridb_facility_id: 232074,
        facility_name: 'Money Creek Campground',
        facility_email: '',
        facility_latitude: 47.721111111111114,
        facility_longitude: -121.39555555555556,
        facility_description: '<h2>Overview</h2>Situated on the banks of the South Fork Skykomish River in Mt. Baker-Snoqualmie National Forest, Money Creek campground offers some of the most stunning scenery in the northern Cascade Range in Washington.<br /><br />Scattered beneath a towering canopy of old-growth forest, the sites in this campground are widely spaced and several are at the rivers edge, making it an ideal setting for visitors wanting to camp in a private, rustic setting. <h4>Natural Features:</h4>Hemmed in by several designated wilderness areas, the Mt. Baker-Snoqualmie National Forest showcases rugged peaks, sparkling alpine lakes and old-growth forests.<br /><br />Mt. Baker, the most prominent feature of the Mt. Baker Wilderness Area, dominates the landscape on a clear day. Rising to an elevation of 10,781 feet, the active volcano from which the forest takes its name is perpetually snow-capped and mantled with an extensive network of creeping glaciers. Mt. Bakers summit, Grant Peak, is actually a 1,300-foot-deep mound of ice, which hides a massive volcanic crater.<br /><br />Wildlife in the area include mountain goats, coyotes, pine marten and a variety of migratory birds and native fish.<h4>Recreation:</h4>In addition to being a prime location for hiking, and fishing in summer and early fall, Money Creek offers excellent skiing and snowshoeing in the winter months.<br /><br /> The Mt. Baker-Snoqualmie National Forests 1,500 miles of trails can entice any hiker to get outdoors. From smooth paths meandering through deep quiet forests to challenging ascents up boulder-studded mountains, opportunities abound for every skill level.<br /><br />Nearby Barclay Creek Trail is an easier hike that follows Barclay Creek through diverse forest until reaching Barclay Lake at an elevation of 2,422 feet. Along the trail, hikers will encounter old growth trees, deer ferns, trillium, wood violets, bleeding hearts and salmon berries in season. Cedar boardwalks lead to a log bridge that crosses Barclay Creek. Once over the bridge, visitors will arrive at the lake and can take in an outstanding view of the north wall of Baring Mountain, dramatically rising 3,700 feet above the lake. <h4>Facilities:</h4>Money Creek campground offers standard sites, accommodating both tent and RV camping. Picnic tables, vault toilets and drinking water are also available.<br /><br /> The nearby Miller River/Money Creek Winter Sports Area is popular base for winter activities.<h4>Nearby Attractions:</h4>The nearby Stevens Pass Historic District offers education on the areas colorful railroad and mining history. The slopes at Stevens Pass Ski Area are only a two hour drive from Money Creek campground.<br /><br /><br /><br /> Visitors enjoy the North Cascades and Mt. Rainer National Parks, where interpretive programs and exhibits offer education about the diverse landscape and history of the area.',
        facility_type_description: 'Camping',
        facility_phone: '541-338-7869',
        facility_map_url: '',
        facility_reservation_url: ' ',
        facility_directions: 'From Everett, Washington, take Highway 2 toward Monroe. From Monroe goeast approximately 30 miles to campground sign. Turn south and travel a mileto campground.',
        keywords: '',
        facility_use_fee_description: '',
        stay_limit: '',
        last_updated_date: new Date('2016-09-08'),
        facility_ada_access: '',
        legacy_facility_id: '70298',
        org_facility_id: 'AN370298',
        facility_address_type: '',
        facility_street_address1: 'Old Cascade Highway',
        facility_street_address2: '',
        facility_street_address3: '',
        city: 'King',
        address_state_code: 'WA',
        postal_code: '98288',
        address_country_code: 'USA'
      }]);
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('facilities_id_seq', (SELECT MAX(id) FROM facilities));"
      );
    });
};
